language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.34.0
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
script:
  - cargo build --verbose --all --all-features
  - cargo clippy --all --all-features -- -D warnings
  - cargo test --verbose --all --all-features
cache: cargo